services:
  api:
    build: .
    container_name: thermaplus_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: ${SQL_CONNECTION}
    restart: unless-stopped