// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Therma_Plus_DotNet.Data;

#nullable disable

namespace Therma_Plus_DotNet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Therma_Plus_DotNet.Models.Regiao", b =>
                {
                    b.Property<int>("RegiaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_regiao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegiaoId"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cidade");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.HasKey("RegiaoId");

                    b.ToTable("TBL_REGIOES");
                });

            modelBuilder.Entity("Therma_Plus_DotNet.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Doenca")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("doenca_cronica");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_regiao");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("TBL_USUARIOS");
                });

            modelBuilder.Entity("Therma_Plus_DotNet.Models.Usuario", b =>
                {
                    b.HasOne("Therma_Plus_DotNet.Models.Regiao", "Regiao")
                        .WithMany("Usuarios")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Therma_Plus_DotNet.Models.Regiao", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
